import Africa from "@/public/Destinations/Continents/Africa.webp";
import Asia from "@/public/Destinations/Continents/Asia.webp";
import Australia from "@/public/Destinations/Continents/Australia.webp";
import Europe from "@/public/Destinations/Continents/Europe.webp";
import NorthAmerica from "@/public/Destinations/Continents/North America.webp";
import SouthAmerica from "@/public/Destinations/Continents/South America.webp";

export const africa = [
  { id: 1, name: "Algeria" },
  { id: 2, name: "Angola" },
  { id: 3, name: "Benin" },
  { id: 4, name: "Botswana" },
  { id: 5, name: "Burkina Faso" },
  { id: 6, name: "Burundi" },
  { id: 7, name: "Cabo Verde" },
  { id: 8, name: "Cameroon" },
  { id: 9, name: "Central African Republic" },
  { id: 10, name: "Chad" },
  { id: 11, name: "Comoros" },
  { id: 12, name: "Democratic Republic of the Congo" },
  { id: 13, name: "Republic of the Congo" },
  { id: 14, name: "Djibouti" },
  { id: 15, name: "Egypt" },
  { id: 16, name: "Equatorial Guinea" },
  { id: 17, name: "Eritrea" },
  { id: 18, name: "Eswatini" },
  { id: 19, name: "Ethiopia" },
  { id: 20, name: "Gabon" },
  { id: 21, name: "Gambia" },
  { id: 22, name: "Ghana" },
  { id: 23, name: "Guinea" },
  { id: 24, name: "Guinea-Bissau" },
  { id: 25, name: "Ivory Coast" },
  { id: 26, name: "Kenya" },
  { id: 27, name: "Lesotho" },
  { id: 28, name: "Liberia" },
  { id: 29, name: "Libya" },
  { id: 30, name: "Madagascar" },
  { id: 31, name: "Malawi" },
  { id: 32, name: "Mali" },
  { id: 33, name: "Mauritania" },
  { id: 34, name: "Mauritius" },
  { id: 35, name: "Morocco" },
  { id: 36, name: "Mozambique" },
  { id: 37, name: "Namibia" },
  { id: 38, name: "Niger" },
  { id: 39, name: "Nigeria" },
  { id: 40, name: "Rwanda" },
  { id: 41, name: "Sao Tome and Principe" },
  { id: 42, name: "Senegal" },
  { id: 43, name: "Seychelles" },
  { id: 44, name: "Sierra Leone" },
  { id: 45, name: "Somalia" },
  { id: 46, name: "South Africa" },
  { id: 47, name: "South Sudan" },
  { id: 48, name: "Sudan" },
  { id: 49, name: "Tanzania" },
  { id: 50, name: "Togo" },
  { id: 51, name: "Tunisia" },
  { id: 52, name: "Uganda" },
  { id: 53, name: "Zambia" },
  { id: 54, name: "Zimbabwe" },
];

export const asia = [
  { id: 1, name: "Afghanistan" },
  { id: 2, name: "Bahrain" },
  { id: 3, name: "Bangladesh" },
  { id: 4, name: "Bhutan" },
  { id: 5, name: "Brunei" },
  { id: 6, name: "Cambodia" },
  { id: 7, name: "China" },
  { id: 8, name: "Cyprus" },
  { id: 9, name: "Georgia" },
  { id: 10, name: "India" },
  { id: 11, name: "Indonesia" },
  { id: 12, name: "Iran" },
  { id: 13, name: "Iraq" },
  { id: 14, name: "Israel" },
  { id: 15, name: "Japan" },
  { id: 16, name: "Jordan" },
  { id: 17, name: "Kazakhstan" },
  { id: 18, name: "Kuwait" },
  { id: 19, name: "Kyrgyzstan" },
  { id: 20, name: "Laos" },
  { id: 21, name: "Lebanon" },
  { id: 22, name: "Malaysia" },
  { id: 23, name: "Maldives" },
  { id: 24, name: "Mongolia" },
  { id: 25, name: "Myanmar (Burma)" },
  { id: 26, name: "Nepal" },
  { id: 27, name: "North Korea" },
  { id: 28, name: "Oman" },
  { id: 29, name: "Pakistan" },
  { id: 30, name: "Palestine" },
  { id: 31, name: "Philippines" },
  { id: 32, name: "Qatar" },
  { id: 33, name: "Russia" },
  { id: 34, name: "Saudi Arabia" },
  { id: 35, name: "Singapore" },
  { id: 36, name: "South Korea" },
  { id: 37, name: "Sri Lanka" },
  { id: 38, name: "Syria" },
  { id: 39, name: "Taiwan" },
  { id: 40, name: "Tajikistan" },
  { id: 41, name: "Thailand" },
  { id: 42, name: "Timor-Leste" },
  { id: 43, name: "Turkey" },
  { id: 44, name: "Turkmenistan" },
  { id: 45, name: "United Arab Emirates" },
  { id: 46, name: "Uzbekistan" },
  { id: 47, name: "Vietnam" },
  { id: 48, name: "Yemen" },
];

export const australia = [
  { id: 1, name: "Australia" },
  { id: 2, name: "Fiji" },
  { id: 3, name: "Kiribati" },
  { id: 4, name: "Marshall Islands" },
  { id: 5, name: "Micronesia" },
  { id: 6, name: "Nauru" },
  { id: 7, name: "New Zealand" },
  { id: 8, name: "Palau" },
  { id: 9, name: "Papua New Guinea" },
  { id: 10, name: "Samoa" },
  { id: 11, name: "Solomon Islands" },
  { id: 12, name: "Tonga" },
  { id: 13, name: "Tuvalu" },
  { id: 14, name: "Vanuatu" },
];

export const europe = [
  { id: 1, name: "Albania" },
  { id: 2, name: "Andorra" },
  { id: 3, name: "Armenia" },
  { id: 4, name: "Austria" },
  { id: 5, name: "Azerbaijan" },
  { id: 6, name: "Belarus" },
  { id: 7, name: "Belgium" },
  { id: 8, name: "Bosnia and Herzegovina" },
  { id: 9, name: "Bulgaria" },
  { id: 10, name: "Croatia" },
  { id: 11, name: "Cyprus" },
  { id: 12, name: "Czech Republic" },
  { id: 13, name: "Denmark" },
  { id: 14, name: "Estonia" },
  { id: 15, name: "Finland" },
  { id: 16, name: "France" },
  { id: 17, name: "Georgia" },
  { id: 18, name: "Germany" },
  { id: 19, name: "Greece" },
  { id: 20, name: "Hungary" },
  { id: 21, name: "Iceland" },
  { id: 22, name: "Ireland" },
  { id: 23, name: "Italy" },
  { id: 24, name: "Kazakhstan" },
  { id: 25, name: "Kosovo" },
  { id: 26, name: "Latvia" },
  { id: 27, name: "Liechtenstein" },
  { id: 28, name: "Lithuania" },
  { id: 29, name: "Luxembourg" },
  { id: 30, name: "Malta" },
  { id: 31, name: "Moldova" },
  { id: 32, name: "Monaco" },
  { id: 33, name: "Montenegro" },
  { id: 34, name: "Netherlands" },
  { id: 35, name: "North Macedonia" },
  { id: 36, name: "Norway" },
  { id: 37, name: "Poland" },
  { id: 38, name: "Portugal" },
  { id: 39, name: "Romania" },
  { id: 40, name: "Russia" },
  { id: 41, name: "San Marino" },
  { id: 42, name: "Serbia" },
  { id: 43, name: "Slovakia" },
  { id: 44, name: "Slovenia" },
  { id: 45, name: "Spain" },
  { id: 46, name: "Sweden" },
  { id: 47, name: "Switzerland" },
  { id: 48, name: "Turkey" },
  { id: 49, name: "Ukraine" },
  { id: 50, name: "United Kingdom" },
  { id: 51, name: "Vatican City" },
];

export const northAmerica = [
  { id: 1, name: "Antigua and Barbuda" },
  { id: 2, name: "Bahamas" },
  { id: 3, name: "Barbados" },
  { id: 4, name: "Belize" },
  { id: 5, name: "Canada" },
  { id: 6, name: "Costa Rica" },
  { id: 7, name: "Cuba" },
  { id: 8, name: "Dominica" },
  { id: 9, name: "Dominican Republic" },
  { id: 10, name: "El Salvador" },
  { id: 11, name: "Grenada" },
  { id: 12, name: "Guatemala" },
  { id: 13, name: "Haiti" },
  { id: 14, name: "Honduras" },
  { id: 15, name: "Jamaica" },
  { id: 16, name: "Mexico" },
  { id: 17, name: "Nicaragua" },
  { id: 18, name: "Panama" },
  { id: 19, name: "Saint Kitts and Nevis" },
  { id: 20, name: "Saint Lucia" },
  { id: 21, name: "Saint Vincent and the Grenadines" },
  { id: 22, name: "Trinidad and Tobago" },
  { id: 23, name: "United States of America" },
];

export const southAmerica = [
  { id: 1, name: "Argentina" },
  { id: 2, name: "Bolivia" },
  { id: 3, name: "Brazil" },
  { id: 4, name: "Chile" },
  { id: 5, name: "Colombia" },
  { id: 6, name: "Ecuador" },
  { id: 7, name: "Guyana" },
  { id: 8, name: "Paraguay" },
  { id: 9, name: "Peru" },
  { id: 10, name: "Suriname" },
  { id: 11, name: "Uruguay" },
  { id: 12, name: "Venezuela" },
];

export const allLocations = [
  {
    id: 1,
    value: "africa",
    label: "Africa",
    map: {
      url: Africa,
      alt: "Map of Africa",
    },
  },
  {
    id: 2,
    value: "asia",
    label: "Asia",
    map: {
      url: Asia,
      alt: "Map of Asia",
    },
  },
  {
    id: 3,
    value: "australia",
    label: "Australia",
    map: {
      url: Australia,
      alt: "Map of Australia",
    },
  },
  {
    id: 4,
    value: "europe",
    label: "Europe",
    map: {
      url: Europe,
      alt: "Map of Europe",
    },
  },
  {
    id: 5,
    value: "north-america",
    label: "North America",
    map: {
      url: NorthAmerica,
      alt: "Map of North America",
    },
  },
  {
    id: 6,
    value: "south-america",
    label: "South America",
    map: {
      url: SouthAmerica,
      alt: "Map of South America",
    },
  },
];
