import Nav from '@/components/UI/Nav/Nav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Agency',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' dark:bg-[#111111]'}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
